RHOAIENG-22439: fix(manifests/rstudio): dismantle the broken RStudio BuildConfig chain and build the image directly
The way it was, the second (dependent) build would always fail on

```
[3/3] STEP 33/37: RUN echo "Installing softwares and packages" && micropipenv install && rm -f ./Pipfile.lock && chmod -R g+w /opt/app-root/lib/python3.11/site-packages && fix-permissions /opt/app-root -P
Installing softwares and packages
/bin/sh: line 1: micropipenv: command not found
error: build error: building at STEP "RUN echo "Installing softwares and packages" && micropipenv install && rm -f ./Pipfile.lock && chmod -R g+w /opt/app-root/lib/python3.11/site-packages && fix-permissions /opt/app-root -P": while running runtime: exit status 127
```

This is because both BuildConfigs were building the same `Dockerfile.cuda` (that's obviously wasteful) and the Dockerfile was not idempotent (and still is not).