wheel
LinkCandidate('https://files.pythonhosted.org/packages/3d/7c/67f4952d1b56b3f74a1
54b97d0dd0630d525923b354db117d04823b8b49b/onnx-1.17.0-cp312-cp312-manylinux_2_17
_x86_64.manylinux2014_x86_64.whl (from https://pypi.org/simple/onnx/)
(requires-python:>=3.8)'), 'protobuf':
LinkCandidate('https://files.pythonhosted.org/packages/8d/14/619e24a4c70df2901e1
f4dbc50a6291eb63a759172558df326347dce1f0d/protobuf-3.20.3-py2.py3-none-any.whl
(from https://pypi.org/simple/protobuf/) (requires-python:>=3.7)'), 'requests':
LinkCandidate('https://files.pythonhosted.org/packages/f9/9b/335f9764261e915ed49
7fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl (from
https://pypi.org/simple/requests/) (requires-python:>=3.8)'), 'six':
LinkCandidate('https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5
921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl (from
https://pypi.org/simple/six/) (requires-python:!=3.0.*,!=3.1.*,!=3.2.*,>=2.7)'),
'certifi':
LinkCandidate('https://files.pythonhosted.org/packages/4a/7e/3db2bd1b1f9e95f7cdd
ca6d6e75e2f2bd9f51b1246e546d88addca0106bd/certifi-2025.4.26-py3-none-any.whl
(from https://pypi.org/simple/certifi/) (requires-python:>=3.6)'),
'charset-normalizer':
LinkCandidate('https://files.pythonhosted.org/packages/8c/73/6ede2ec59bce19b3edf
4209d70004253ec5f4e319f9a2e3f2f15601ed5f7/charset_normalizer-3.4.2-cp312-cp312-m
anylinux_2_17_x86_64.manylinux2014_x86_64.whl (from
https://pypi.org/simple/charset-normalizer/) (requires-python:>=3.7)'), 'idna':
LinkCandidate('https://files.pythonhosted.org/packages/76/c6/c88e154df9c4e1a2a66
ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl (from
https://pypi.org/simple/idna/) (requires-python:>=3.6)'), 'urllib3':
LinkCandidate('https://files.pythonhosted.org/packages/6b/11/cc635220681e93a0183
390e26485430ca2c7b5f9d33b15c74c2861cb8091/urllib3-2.4.0-py3-none-any.whl (from
https://pypi.org/simple/urllib3/) (requires-python:>=3.9)')}),
criteria={'tf2onnx': Criterion((SpecifierRequirement('tf2onnx~=1.16.1'),
via=None)), 'numpy': Criterion((SpecifierRequirement('numpy>=1.14.1'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3f/48/826db3d02645d84
e7ee5d5ce8407f771057d40fe224d9c3e89536674ccef/tf2onnx-1.16.1-py3-none-any.whl
(from https://pypi.org/simple/tf2onnx/)')),
(SpecifierRequirement('numpy>=1.20'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3d/7c/67f4952d1b56b3f
74a154b97d0dd0630d525923b354db117d04823b8b49b/onnx-1.17.0-cp312-cp312-manylinux_
2_17_x86_64.manylinux2014_x86_64.whl (from https://pypi.org/simple/onnx/)
(requires-python:>=3.8)'))), 'onnx':
Criterion((SpecifierRequirement('onnx>=1.4.1'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3f/48/826db3d02645d84
e7ee5d5ce8407f771057d40fe224d9c3e89536674ccef/tf2onnx-1.16.1-py3-none-any.whl
(from https://pypi.org/simple/tf2onnx/)'))), 'requests':
Criterion((SpecifierRequirement('requests'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3f/48/826db3d02645d84
e7ee5d5ce8407f771057d40fe224d9c3e89536674ccef/tf2onnx-1.16.1-py3-none-any.whl
(from https://pypi.org/simple/tf2onnx/)'))), 'six':
Criterion((SpecifierRequirement('six'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3f/48/826db3d02645d84
e7ee5d5ce8407f771057d40fe224d9c3e89536674ccef/tf2onnx-1.16.1-py3-none-any.whl
(from https://pypi.org/simple/tf2onnx/)'))), 'flatbuffers':
Criterion((SpecifierRequirement('flatbuffers>=1.12'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3f/48/826db3d02645d84
e7ee5d5ce8407f771057d40fe224d9c3e89536674ccef/tf2onnx-1.16.1-py3-none-any.whl
(from https://pypi.org/simple/tf2onnx/)'))), 'protobuf':
Criterion((SpecifierRequirement('protobuf~=3.20'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3f/48/826db3d02645d84
e7ee5d5ce8407f771057d40fe224d9c3e89536674ccef/tf2onnx-1.16.1-py3-none-any.whl
(from https://pypi.org/simple/tf2onnx/)')),
(SpecifierRequirement('protobuf>=3.20.2'),
via=LinkCandidate('https://files.pythonhosted.org/packages/3d/7c/67f4952d1b56b3f
74a154b97d0dd0630d525923b354db117d04823b8b49b/onnx-1.17.0-cp312-cp312-manylinux_
2_17_x86_64.manylinux2014_x86_64.whl (from https://pypi.org/simple/onnx/)
(requires-python:>=3.8)'))), 'charset-normalizer':
Criterion((SpecifierRequirement('charset-normalizer<4,>=2'),
via=LinkCandidate('https://files.pythonhosted.org/packages/f9/9b/335f9764261e915
ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl
(from https://pypi.org/simple/requests/) (requires-python:>=3.8)'))), 'idna':
Criterion((SpecifierRequirement('idna<4,>=2.5'),
via=LinkCandidate('https://files.pythonhosted.org/packages/f9/9b/335f9764261e915
ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl
(from https://pypi.org/simple/requests/) (requires-python:>=3.8)'))), 'urllib3':
Criterion((SpecifierRequirement('urllib3<3,>=1.21.1'),
via=LinkCandidate('https://files.pythonhosted.org/packages/f9/9b/335f9764261e915
ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl
(from https://pypi.org/simple/requests/) (requires-python:>=3.8)'))), 'certifi':
Criterion((SpecifierRequirement('certifi>=2017.4.17'),
via=LinkCandidate('https://files.pythonhosted.org/packages/f9/9b/335f9764261e915
ed497fcdeb11df5dfd6f7bf257d4a6a2a686d80da4d54/requests-2.32.3-py3-none-any.whl
(from https://pypi.org/simple/requests/) (requires-python:>=3.8)')))},
backtrack_causes=[]))
INFO:pipenv.patched.pip._internal.network.download:Downloading
tf2onnx-1.16.1-py3-none-any.whl (455 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
flatbuffers-25.2.10-py2.py3-none-any.whl (30 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0
MB)
INFO:pipenv.patched.pip._internal.network.download:Downloading
onnx-1.17.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
INFO:pipenv.patched.pip._internal.network.download:Downloading
protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
requests-2.32.3-py3-none-any.whl (64 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
six-1.17.0-py2.py3-none-any.whl (11 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
certifi-2025.4.26-py3-none-any.whl (159 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
charset_normalizer-3.4.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.
whl (148 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
idna-3.10-py3-none-any.whl (70 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached
urllib3-2.4.0-py3-none-any.whl (128 kB)
Success!
Updated Pipfile.lock
(c5d33a8cbedb59e86aab051df7f02c333d9f4a6518d6c32955f204663b1a7f5f)!
+ for dir in $DIRS
Processing directory: jupyter/trustyai/ubi9-python-3.12
+ echo 'Processing directory: jupyter/trustyai/ubi9-python-3.12'
+ cd /home/runner/work/notebooks/notebooks
+ '[' -d jupyter/trustyai/ubi9-python-3.12 ']'
+ echo 'Updating 3.12 Pipfile.lock in jupyter/trustyai/ubi9-python-3.12'
+ cd jupyter/trustyai/ubi9-python-3.12
+ '[' -f Pipfile ']'
+ pipenv lock --verbose
Updating 3.12 Pipfile.lock in jupyter/trustyai/ubi9-python-3.12
Using python: 3.12
Path to python: /opt/hostedtoolcache/Python/3.12.10/x64/bin/python3
Creating a virtualenv for this project
Pipfile:
/home/runner/work/notebooks/notebooks/jupyter/trustyai/ubi9-python-3.12/Pipfile
Using /opt/hostedtoolcache/Python/3.12.10/x64/bin/python33.12.10 to create
virtualenv...
created virtual environment CPython3.12.10.final.0-64 in 95ms
  creator
CPython3Posix(dest=/home/runner/.local/share/virtualenvs/ubi9-python-3.12-6E0y9i
g3, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy,
app_data_dir=/home/runner/.local/share/virtualenv)
    added seed packages: pip==25.1.1
  activators
BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator
,PythonActivator
Successfully created virtual environment!
Virtualenv location: /home/runner/.local/share/virtualenvs/ubi9-python-3.12-6E0y9ig3
Locking  dependencies...
Building requirements...
Resolving dependencies...
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starti
ng()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding
_requirement(SpecifierRequirement('mysql-connector-python~=9.2.0'), None)
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting
mysql-connector-python~=9.2.0 (from -r
/tmp/pipenv-gl491utg-requirements/pipenv-v_7if9mw-constraints.txt (line 15))
INFO:pipenv.patched.pip._internal.network.download:Using cached
mysql_connector_python-9.2.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.0
kB)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding
_requirement(SpecifierRequirement('scikit-learn~=1.2.1'), None)
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting
scikit-learn~=1.2.1 (from -r
/tmp/pipenv-gl491utg-requirements/pipenv-v_7if9mw-constraints.txt (line 35))
INFO:pipenv.patched.pip._internal.network.download:Downloading
scikit-learn-1.2.2.tar.gz (7.3 MB)
INFO:pipenv.patched.pip._internal.cli.spinners:Installing build dependencies:
started
INFO:pipenv.patched.pip._internal.cli.spinners:Installing build dependencies:
finished with status 'done'
INFO:pipenv.patched.pip._internal.cli.spinners:Getting requirements to build
wheel: started
INFO:pipenv.patched.pip._internal.cli.spinners:Getting requirements to build
wheel: finished with status 'done'
INFO:pipenv.patched.pip._internal.cli.spinners:Preparing metadata
(pyproject.toml): started
INFO:pipenv.patched.pip._internal.cli.spinners:Preparing metadata
(pyproject.toml): finished with status 'error'
ERROR:pip.subprocessor:Preparing metadata (pyproject.toml) exited with 1
Traceback (most recent call last):
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/utils/misc.py", line 723, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_vendor/pyproject_hooks/_impl.py", line 224, in
prepare_metadata_for_build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_vendor/pyproject_hooks/_impl.py", line 392, in _call_hook
    self._subprocess_runner(
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/utils/subprocess.py", line 237, in runner
    call_subprocess(
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/utils/subprocess.py", line 209, in call_subprocess
    raise error
pipenv.patched.pip._internal.exceptions.InstallationSubprocessError: Preparing
metadata (pyproject.toml) exited with 1
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/uti
ls/resolver.py", line 472, in resolve
    results = resolver.resolve(self.constraints, check_supported_wheels=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in
__bool__
    return any(self)
           ^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in
<genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in
_iter_built
    candidate = func()
                ^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/factory.py", line 187, in
_make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/factory.py", line 233, in
_make_base_candidate_from_link
    self._link_candidate_cache = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/candidates.py", line 308, in __init__
    super().__init__(
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/candidates.py", line 160, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/candidates.py", line 237, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/resolution/resolvelib/candidates.py", line 319, in
_prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/operations/prepare.py", line 527, in
prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/operations/prepare.py", line 642, in
_prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/operations/prepare.py", line 72, in
_get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/distributions/sdist.py", line 69, in
prepare_distribution_metadata
    self.req.prepare_metadata()
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/req/req_install.py", line 576, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/pat
ched/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pipenv.patched.pip._internal.exceptions.MetadataGenerationFailed: metadata
generation failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/res
olver.py", line 465, in <module>
    main()
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/res
olver.py", line 451, in main
    _main(
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/res
olver.py", line 436, in _main
    resolve_packages(
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/res
olver.py", line 400, in resolve_packages
    results, resolver = resolve_deps(
                        ^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/uti
ls/resolver.py", line 979, in resolve_deps
    results, hashes, internal_resolver = actually_resolve_deps(
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/uti
ls/resolver.py", line 747, in actually_resolve_deps
    resolver.resolve()
  File
"/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/pipenv/uti
ls/resolver.py", line 474, in resolve
    raise ResolutionFailure(message=e)
pipenv.exceptions.ResolutionFailure: ERROR: metadata generation failed
Locking Failed!
Your dependencies could not be resolved. You likely have a mismatch in your
sub-dependencies.
You can use $ pipenv run pip install <requirement_name> to bypass this
mechanism, then run $ pipenv graph to inspect the versions actually installed in
the virtualenv.
Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Failed to lock Pipfile.lock!
make: *** [Makefile:418: refresh-pipfilelock-files] Error 1
Error: Process completed with exit code 2.